sudo: false
language: rust
rust:
    - stable
    - beta
    - nightly
before_script:
    - pip install 'travis-cargo>=0.1.0,<0.2.0' --user
    - pip install 'CppHeaderParser>=2.7.2,<3.0.0' --user
    - export PATH="$HOME/.local/bin:$PATH"
    - git clone https://github.com/arcnmx/cargo-clippy.git
    - cd cargo-clippy
    - travis-cargo --only nightly build
    - export PATH="$PWD/target/debug:$PATH"
    - cd ..
script:
    - travis-cargo build
    - ./on-nightly cargo clippy --lib
    - ./on-nightly cargo clippy --bin cheddar
    - travis-cargo test
    - travis-cargo --only stable doc
env:
    global:
        - RUST_BACKTRACE=1
        - TRAVIS_CARGO_NIGHTLY_FEATURE=""
